### ISSUE TITLE
How connect to pancake swap from nodejs

### ISSUE THREAD

**Issue by rabinhod** [pancakeswap/pancake-swap-interface#147]
Hi
how can i connect to pancake swap with nodejs ?
is there any document about it ?

how trust wallet connect to pancake swap ?

**Comment by RabbitDoge** [comment]
Can you be more specific ? Are you looking for some kind of API ?

**Comment by rabinhod** [comment]
Yes I'm looking for some kind of API or nodejs library

**Comment by RabbitDoge** [comment]
We don't provide any public api. The best way for you to interact with pancake, is to interact directly with the nodes.
Can you explain what you want to do ? I can provide you some guidance.

**Comment by takamaka-1337** [comment]
I would like to connect it through python and would like to do SWAPs via CLI. Can you provide me some guidance?

**Comment by jsheng08** [comment]
@rabinhod @takamaka-1337 the best way is to use web3 to call the swap.
Since Binance Smart Chain is based on ETH Web3 js. Any ETH guide is usable. Check the BSC guide here.
https://docs.binance.org/smart-chain/developer/create-wallet.html

You can call the swapExactETHForTokens or swapETHForExactTokens on the contract (This contract below is a BUSD-BNB pair)
https://bscscan.com/address/0x05ff2b0db69458a0750badebc4f9e13add608c7f#writeContract

To execute smartcontract on python or nodejs, you need to download the abi (can be found on the bscscan) and then execute the function you want.

Hope this helps

**Comment by takamaka-1337** [comment]
Thank you very much, this is it! :)
