### ISSUE TITLE
[Listing] Request listing for Freedom Reserve

### ISSUE THREAD

**Issue by AcapSLP** [pancakeswap/pancake-swap-interface#222]
### Declaration

[X] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
[X] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: Freedom Reserve

Token symbol: bFR

Token address: 0xBea7086c99A85D4b5E6A0494C18B037fDD8eE932

Token decimals: 18

Project website: https://freedomreserv.eth.link

```

### Logo

Please upload your logo in .png format with a size of 96\*96px
![frlogo96x96](https://user-images.githubusercontent.com/72445644/109199322-34879580-7797-11eb-8400-f8c7b6281482.png)

**Comment by AcapSLP** [comment]
what are the requirements? we can be contacted on freedomreserv@ethmail.cc regarding syrup pool

**Comment by Chef-Chungus** [comment]
Due to high demand we have instated the following rule to keep our GitHub tidy: 

### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM

Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform

Any Listing issues/PRs will be closed.
