### ISSUE TITLE
[Listing] Request listing for Agus Finance

### ISSUE THREAD

**Issue by agussaifuddin** [pancakeswap/pancake-swap-interface#230]
### Declaration

[X] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
[X] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: Agus Finance

Token symbol: AFI

Token address: 0x246988285b48efd26488426fbc785074e7cdf148

Token decimals: 18

Project website: https://agus.finance
```
### Logo

![AFI](https://user-images.githubusercontent.com/40567253/109381850-962c2a80-7891-11eb-9a9a-997aff851c16.png)

**Comment by agussaifuddin** [comment]
@Chef-Chungus please approve AFI so that my little project has a market to and we can grow.

thank you

**Comment by nusantaratoken** [comment]
I support you sir 💪 I hope afi listed on Pancakeswap 🎉

**Comment by agussaifuddin** [comment]
> I support you sir 💪 I hope afi listed on Pancakeswap 🎉

thank you

**Comment by Chef-Chungus** [comment]
Due to high demand we have instated the following rule to keep our GitHub tidy: 

### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM

Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform

Any Listing issues/PRs will be closed.
