### ISSUE TITLE
[Listing] Request listing for SWAPTOKEN

### ISSUE THREAD

**Issue by NotEternal** [pancakeswap/pancake-swap-interface#231]
### Declaration

- [x] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
- [x] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: SWAPTOKEN

Token symbol: SWAP

Token address: 0x92648e4537cdfa1ee743a244465a31aa034b1ce8

Token decimals: 18

Project website: https://swaponline.io/
```

### Logo

![swap](https://user-images.githubusercontent.com/61930014/109411813-77916680-7959-11eb-971e-0e64d8ca43ff.png)

**Comment by Chef-Chungus** [comment]
Due to high demand we have instated the following rule to keep our GitHub tidy: 

### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM

Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform

Any Listing issues/PRs will be closed.

**Comment by NotEternal** [comment]
Understood. Maybe will better to delete pull request option from list) [here](https://github.com/pancakeswap/pancake-swap-interface/blob/master/listing.md)
