### ISSUE TITLE
[Listing] Request listing for {ADD TOKEN NAME HERE}

### ISSUE THREAD

**Issue by dogdefi** [pancakeswap/pancake-swap-interface#237]
### Declaration

[ ] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
[X] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: DogDeFi Shares

Token symbol:DogDeFiS 

Token address: 0x64fd230eb6e1dbb2e6e1e00d6b048d033337021e

Token decimals: 18 

Project website: http://dogdeficoin.com
```

### Logo

Please upload your logo in .png format with a size of 96\*96px
https://dogdeficoin.com/wp-content/uploads/2021/02/LOGO-SHARES.png

**Comment by dogdefi** [comment]
we list today dogdefi shares and we can find a link to our pair BNB/DogDeFiS   -work only search for address contract

**Comment by Chef-Chungus** [comment]
Due to high demand we have instated the following rule to keep our GitHub tidy: 

### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM

Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform

Any Listing issues/PRs will be closed.
