### ISSUE TITLE
[Listing] Request listing for {BSCCORE FINANCE}

### ISSUE THREAD

**Issue by bscfinance** [pancakeswap/pancake-swap-interface#240]
### Declaration

[* ] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
[ *] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information
DEFI YIELD IPTMIZER PROTOCOL ON BINANCE SMART CHAIN

BSCCORE FINANCE GOAL IS TO PROVIDE A USER FRIENDLY APPLICATION SERVICES AND PRODUCTS FOR DECENTRALIZED FINANCE.

BSC Tokens  incentivize its participants through various yield farming/staking oppurtunities.
BSC Core Vault’s goal is to maximize LP staker’s profits and to constantly improve and develop the protocol to produce competitive Yields.
```
Token name: BSCCORE FINANCE

Token symbol:BSC

Token address: 0xf5128928f85F16bD67C1E02DdD1b47A71d17aDF5

Token decimals:18 

Project website: https://www.bscfinance.org/
```

### Logo
![BSC](https://user-images.githubusercontent.com/79234690/109651851-fecd1d00-7b99-11eb-99b2-2bb04760a1ec.png)

Please upload your logo in .png format with a size of 96\*96px

**Comment by Chef-Chungus** [comment]
Due to high demand we have instated the following rule to keep our GitHub tidy: 

### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM

Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform

Any Listing issues/PRs will be closed.
