### ISSUE TITLE
[Listing] Request listing for Curio Governance Token

### ISSUE THREAD

**Issue by sushkov** [pancakeswap/pancake-swap-interface#244]
### Declaration

- [x] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
- [x] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: Curio Governance Token

Token symbol: CGT

Token address: 0x3d04edc843e74935c09f54cc4b2fe1870e347ac9

Token decimals: 18

Project website: https://curioinvest.com/curio-stablecoin
```

### Logo

Please upload your logo in .png format with a size of 96\*96px
![CGT-96](https://user-images.githubusercontent.com/6535963/109833554-69da2a80-7c52-11eb-9cdc-87e6effff8dd.png)

**Comment by Chef-Chungus** [comment]
Due to high demand we have instated the following rule to keep our GitHub tidy: 

### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM

Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform

Any Listing issues/PRs will be closed.
