### ISSUE TITLE
[Listing] Request listing for Travala.com Token (AVA)

### ISSUE THREAD

**Issue by Brainriver** [pancakeswap/pancake-swap-interface#248]
### Declaration

[] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
[x] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: Travala.com Token (AVA)

Token symbol: AVA

Token address: 0x13616F44Ba82D63c8C0DC3Ff843D36a8ec1c05a9

Token decimals: 18

Project website: https://www.travala.com/
```

### Logo
![travala](https://user-images.githubusercontent.com/1178957/110022796-ab3f0880-7d2c-11eb-8100-0ebf58fad8ad.png)
Please upload your logo in .png format with a size of 96\*96px

**Comment by Chef-Chungus** [comment]
Due to high demand we have instated the following rule to keep our GitHub tidy: 

### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM

Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform

Any Listing issues/PRs will be closed.
