### ISSUE TITLE
[Listing] Request listing for Nerve ($NRV)

### ISSUE THREAD

**Issue by nerve-finance** [pancakeswap/pancake-swap-interface#254]
### Declaration

[x] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
[x] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: Nerve

Token symbol: NRV

Token address: 0x42F6f551ae042cBe50C739158b4f0CAC0Edb9096

Token decimals: 18

Project website: https://nerve.fi
```

### Logo

Please upload your logo in .png format with a size of 96\*96px

![NerveLogoIcon_96x96](https://user-images.githubusercontent.com/79606691/110226401-d3f60800-7ebc-11eb-97c5-3c0a15a03cac.png)

**Comment by Chef-Chungus** [comment]
Due to high demand we have instated the following rule to keep our GitHub tidy: 

### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM

Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform

Any Listing issues/PRs will be closed.
