### ISSUE TITLE
[Listing] Request listing for SALT

### ISSUE THREAD

**Issue by saltPink** [pancakeswap/pancake-swap-interface#255]
### Declaration

[x] I confirm that I have filled out the PancakeSwap Syprup pool or IFO application
[x] I understand that if I have not submitted an application for a Syrup pool or IFO, my PR/issue will be closed.

### Token information

```
Token name: SALT

Token symbol: SALT

Token address: 0x2849b1aE7E04A3D9Bc288673A92477CF63F28aF4

Token decimals: 18

Project website: https://saltswap.finance


```

### Logo

Please upload your logo in .png format with a size of 96\*96px
![salt96](https://user-images.githubusercontent.com/79117470/110254843-91562d80-7f99-11eb-95d6-d9746ddf605c.png)

**Comment by Chef-Chungus** [comment]
Due to high demand we have instated the following rule to keep our GitHub tidy: 

### DO NOT SUBMIT A LISTING REQUEST ON GITHUB - WE WILL LIST ANY PROJECT THAT HAS AN IFO/POOL/FARM

Please apply here instead: https://docs.google.com/forms/d/e/1FAIpQLScGdT5rrVMr4WOWr08pvcroSeuIOtEJf1sVdQGVdcAOqryigQ/viewform

Any Listing issues/PRs will be closed.
