### ISSUE TITLE
.env files not working for local Ganache deployment 

### ISSUE THREAD

**Issue by user24802408424** [pancakeswap/pancake-swap-interface#309]
Trying to do some tests for a Dapp using the interface, would like to connect this to my local blockchain environment. Yet every time setting the .env.development / .env.production files, it keeps defaulting to the BSC Mainnet. Some advice would be appreciated.

**Comment by RabbitDoge** [comment]
https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by Chef-Cheems** [comment]
It should work with this setup in your `.env.development.local` (assuming default Ganache chainId and port number):
```
REACT_APP_CHAIN_ID = "1337"
REACT_APP_NODE_1 = "HTTP://127.0.0.1:7545"
REACT_APP_NODE_2 = "HTTP://127.0.0.1:7545"
REACT_APP_NODE_3 = "HTTP://127.0.0.1:7545"
```

Keep in mind that since your local ganache doesn't have any PCS contracts it it out of the box you'll have to also:
1. Deploy PCS contracts to Ganache
2. Put your local Ganache contract addresses into `src/config/constants/`

**Comment by user24802408424** [comment]
thankyou for the responses, that clears things up
